version: '3.9'

services:
  db-test:
    image: postgres:latest
    restart: always
    container_name: prisma-database
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=tests
    ports:
      - 5433:5432
