version: '3.7'

services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./apps/api/.env
    ports:
      - '5432:5432'

  db-test:
    image: postgres:latest
    env_file: ./apps/api/.env.test
    ports:
      - 5433:5432

volumes:
  data:
