version: '3.8'

services:
  hive-mind-api:
    container_name: hivemind-api
    hostname: api.hive-mind.app
    env_file:
      - apps/api/.env.local
    image: benediktms/hive-mind-api
    ports:
      - 3001:3001
    network_mode: host
    restart: on-failure

  hive-mind-web:
    container_name: hivemind-web
    hostname: hive-mind.app
    env_file:
      - apps/web/.env.local
    image: benediktms/hive-mind-web
    ports:
      - 3000:3000
    depends_on:
      - hive-mind-api
    restart: on-failure
