version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    container_name: grp-database
    env_file: .env
    ports:
      - '5432:5432'

volumes:
  data:
