version: '3.3'

services:
  hive-mind-api:
    container_name: hivemind-api
    hostname: api.hive-mind.app
    env_file:
      - ./.env
    image: benediktms/hive-mind-api
    ports:
      - 3001:3001
    restart: on-failure
    labels:
      # - 'traefik.http.routers.hivemind-api.rule=Host(`hivemind-api.docker.localhost:3001`)'
      - 'traefik.http.routers.hivemind-api.rule=Host(`hive-mind.app`)'
    networks:
      - traefik-public

  hive-mind-web:
    container_name: hivemind-web
    hostname: hive-mind.app
    env_file:
      - ./.env
    image: benediktms/hive-mind-web
    ports:
      - 3000:3000
    depends_on:
      - hive-mind-api
    restart: on-failure
    labels:
      # - 'traefik.http.routers.hivemind-web.rule=Host(`hivemind-web.docker.localhost`)'
      - 'traefik.http.routers.hivemind-api.rule=Host(`api.hive-mind.app`)'
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
