name: CI - Check Branch
on: [push, pull_request]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NEXT_PUBLIC_API_URI: http://example.com
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/grp

jobs:
  check-branch:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: grp
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Migrate DB & generate prisma client
        run: yarn prisma migrate deploy

      - name: Start agents
        run: npx nx-cloud start-ci-run

      - name: Build
        run: npx nx affected --target=build --parallel --max-parallel=3

      - name: Lint
        run: npx nx affected --target=lint --parallel --max-parallel=2

      - name: Test
        run: npx nx affected --target=test --parallel --max-parallel=2

      - name: End-to-end
        run: npx nx affected --target=e2e --parallel --max-parallel=2

      - name: Stop agents
        run: npx nx-cloud stop-all-agents

  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install --frozen-lockfile
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
