name: CI - Check Branch
on: [push]

jobs:
  check-branch:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://prisma:prisma@localhost:5433/tests

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: tests
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install
      - run: npx nx affected --target=build --parallel --max-parallel=3
      - run: npx nx affected --target=lint --parallel --max-parallel=2
      - run: npx nx affected --target=test --parallel --max-parallel=2
