name: CI - Deploy
on:
  push:
    branches:
      - prod

jobs:
  cancel-previous:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

  check-branch:
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost/test?schema=public
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Lint
        run: npx nx affected --target=lint --parallel --max-parallel=2
      - name: Migrate DB & generate prisma client
        run: yarn prisma migrate deploy
      - name: Test
        run: npx nx affected --target=test --parallel --max-parallel=2

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: ['api', 'web']
    env:
      NEXT_PUBLIC_API_URI: https://api.hive-mind.app
    steps:
      - uses: actions/checkout@v3
      - name: List versions
        run: |
          docker --version
          docker-compose --version
      - name: Build
        shell: bash
        env:
          COMMIT_HASH: ${{ github.sha }}
        run: yarn docker:build:${{ matrix.services }}
      - name: List images
        run: docker image ls
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push images
        working-directory: docker
        run: docker push benediktms/hive-mind-${{ matrix.services }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DEPLOY_HOST: benedikt@hive-mind.app
      DEPLOY_PATH: /srv/hivemind
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add ssh key
        shell: bash
        run: |
          echo "$SSH_KEY" > /tmp/ssh-key
          chmod 600 /tmp/ssh-key
      - name: Echo SSH key
        run: echo /tmp/ssh-key
      - name: rsync to remote
        shell: bash
        working-directory: docker
        run: |
          rsync \
            --verbose \
            --recursive \
            --checksum \
            --rsh "ssh -i /tmp/ssh-key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
            ./ $DEPLOY_HOST:$DEPLOY_PATH
      - name: start container images
        shell: bash
        run: |
          ssh \
          -i /tmp/ssh-key \
          -o UserKnownHostsFile=/dev/null \
          -o StrictHostKeyChecking=no \
          -n \
          $DEPLOY_HOST \
          "cd $DEPLOY_PATH &&\
          ./scripts/build.sh &&\
          ./scripts/run-migrations.sh"
